version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: yugioh-api-dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
