name: 🐞 Reporte de Bug
description: Crear un reporte para ayudarnos a mejorar
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarse el tiempo de completar este reporte de bug.
  - type: textarea
    id: descripcion
    attributes:
      label: Describe el bug
      description: Una descripción clara y concisa del bug.
    validations:
      required: true
  - type: textarea
    id: reproducir
    attributes:
      label: Pasos para reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '....'
        3. Desplazarse hasta '....'
        4. Ver el error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Una descripción clara y concisa de lo que esperabas que ocurriera.
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Entorno
      description: ¿Dónde ocurre el problema?
      options:
        - Desarrollo local
        - Contenedor Docker
        - Entorno de producción
        - Otro (especificar en comentarios)
    validations:
      required: true
  - type: textarea
    id: contexto
    attributes:
      label: Información adicional
      description: Añade cualquier otro contexto sobre el problema aquí.
