name: 游눠 Solicitud de Caracter칤stica
description: Sugerir una idea para este proyecto
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por sugerir una nueva caracter칤stica. Tu feedback es valioso para mejorar el proyecto.
  - type: textarea
    id: problema
    attributes:
      label: 쯉u solicitud de funci칩n est치 relacionada con un problema?
      description: Una descripci칩n clara y concisa del problema. Ej. Siempre me frustra cuando [...]
    validations:
      required: false
  - type: textarea
    id: solucion
    attributes:
      label: Describa la soluci칩n que le gustar칤a
      description: Una descripci칩n clara y concisa de lo que quiere que suceda.
    validations:
      required: true
  - type: textarea
    id: alternativas
    attributes:
      label: Describa las alternativas que ha considerado
      description: Una descripci칩n clara y concisa de cualquier soluci칩n o caracter칤stica alternativa que haya considerado.
    validations:
      required: false
  - type: textarea
    id: contexto
    attributes:
      label: Contexto adicional
      description: A침ada cualquier otro contexto o capturas de pantalla sobre la solicitud de caracter칤stica aqu칤.
